### ISSUE TITLE
[Bug] Error: Backend(NotEnoughMemory(64)) when deploying Gemma-2B on v5e-8

### ISSUE THREAD

**Issue by Edwinhr716** [huggingface/optimum-tpu#148]
Whenever running Gemma-2B, I get this error

```
    enable_prefill_logprobs: false,
}
2025-03-24T09:41:57.263923Z  INFO hf_hub: Token file not found "/data/token"    
2025-03-24T09:41:58.843958Z  WARN text_generation_launcher::gpu: Cannot determine GPU compute capability: AssertionError: Torch not compiled with CUDA enabled
2025-03-24T09:41:58.843997Z  INFO text_generation_launcher: Using attention flashinfer - Prefix caching true
2025-03-24T09:41:58.845075Z  INFO text_generation_launcher: Default `max_batch_prefill_tokens` to 4096
2025-03-24T09:41:58.845088Z  INFO text_generation_launcher: Using default cuda graphs [1, 2, 4, 8, 16, 32]
2025-03-24T09:41:58.845192Z  INFO download: text_generation_launcher: Starting check and download process for google/gemma-2b
2025-03-24T09:41:59.003585Z  WARN text_generation_launcher: 'extension' argument is not supported and will be ignored.
2025-03-24T09:41:59.003622Z  WARN text_generation_launcher: 'merge_lora' argument is not supported and will be ignored.
2025-03-24T09:42:28.063858Z  INFO download: text_generation_launcher: Successfully downloaded weights for google/gemma-2b
2025-03-24T09:42:28.064165Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2025-03-24T09:42:28.216280Z  INFO text_generation_launcher: 'otlp_service_name' argument is not supported and will be ignored.
2025-03-24T09:42:38.076088Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:42:47.980308Z  WARN text_generation_launcher: Revision is not supported for JetStream/Pytorch engine, ignoring.
2025-03-24T09:42:47.980343Z  INFO text_generation_launcher: Loading model engine (this can take a few minutes).
2025-03-24T09:42:47.981812Z  INFO text_generation_launcher: Creating engine with max_cache_length=512 = 256 + 256
2025-03-24T09:42:48.090899Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:42:58.155411Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:43:08.157279Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:43:18.229776Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:43:28.237030Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:43:31.388944Z  INFO text_generation_launcher: Engine successfully loaded in 43.41 s.
2025-03-24T09:43:33.061304Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
2025-03-24T09:43:33.155800Z  INFO shard-manager: text_generation_launcher: Shard ready in 65.083832643s rank=0
2025-03-24T09:43:33.158856Z  INFO text_generation_launcher: Starting Webserver
2025-03-24T09:43:33.175556Z  INFO text_generation_router_v2: backends/v2/src/lib.rs:88: Warming up model
2025-03-24T09:43:33.176214Z  INFO text_generation_launcher: Warmup (this can take several minutes)
2025-03-24T09:44:29.968240Z  INFO text_generation_launcher: Warmup done
Error: Backend(NotEnoughMemory(512))
2025-03-24T09:44:30.065151Z ERROR text_generation_launcher: Webserver Crashed
2025-03-24T09:44:30.065196Z  INFO text_generation_launcher: Shutting down shards
2025-03-24T09:44:30.079378Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=0
2025-03-24T09:44:30.079433Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=0
2025-03-24T09:44:41.666741Z  INFO shard-manager: text_generation_launcher: shard terminated rank=0
Error: WebserverFailed
markchen@cloudshell:~ (leadership-hpc-discovery)$ kubectl delete deployment tgi-tpu -n default
deployment.apps "tgi-tpu" deleted
markchen@cloudshell:~ (leadership-hpc-discovery)$ kubectl apply -f optimum-tpu-gemma-2b-2x4.yaml
deployment.apps/tgi-tpu created
service/service unchanged
markchen@cloudshell:~ (leadership-hpc-discovery)$ kubectl logs -f -l app=tgi-tpu
2025-03-24T09:49:52.518609Z  WARN text_generation_launcher: Revision is not supported for JetStream/Pytorch engine, ignoring.
2025-03-24T09:49:52.518650Z  INFO text_generation_launcher: Loading model engine (this can take a few minutes).
2025-03-24T09:49:52.520093Z  INFO text_generation_launcher: Creating engine with max_cache_length=64 = 32 + 32
2025-03-24T09:49:58.281583Z  INFO text_generation_launcher: Engine successfully loaded in 5.76 s.
2025-03-24T09:49:58.394781Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2025-03-24T09:49:59.446601Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
2025-03-24T09:49:59.496175Z  INFO shard-manager: text_generation_launcher: Shard ready in 21.166552111s rank=0
2025-03-24T09:49:59.590347Z  INFO text_generation_launcher: Starting Webserver
2025-03-24T09:49:59.622067Z  INFO text_generation_router_v2: backends/v2/src/lib.rs:88: Warming up model
2025-03-24T09:49:59.622640Z  INFO text_generation_launcher: Warmup (this can take several minutes)
2025-03-24T09:50:29.540135Z  INFO text_generation_launcher: Warmup done
Error: Backend(NotEnoughMemory(64))
2025-03-24T09:50:29.627611Z ERROR text_generation_launcher: Webserver Crashed
2025-03-24T09:50:29.627637Z  INFO text_generation_launcher: Shutting down shards
2025-03-24T09:50:29.635506Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=0
2025-03-24T09:50:29.635561Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=0
2025-03-24T09:50:39.928556Z  INFO shard-manager: text_generation_launcher: shard terminated rank=0
Error: WebserverFailed
```

I have tested it out using head, and using the v0.2.3 release, got the error on both. Had to go back to v0.1.3 to get it working.

**Comment by tengomucho** [comment]
I think this might be an issue with the batch size and the sequence length. I see you are deploying on a 2x4, I guess there you could probable use these settings: `MAX_INPUT_LENGTH=8191 MAX_BATCH_PREFILL_TOKENS=32768 MAX_TOTAL_LENGTH=8192 MAX_BATCH_SIZE=16`. These settings should allow to turn the model without issues.

**Comment by Edwinhr716** [comment]
Thanks, that worked!
